apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-app

spec:
  type: LoadBalancer
  ports:
    - port: 8765
      targetPort: 8765
  selector:
    app: example-app
